# Generated by Django 4.2.3 on 2023-07-28 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField(blank=True, default=None, null=True)),
                ('last_name', models.TextField(blank=True, default=None, null=True)),
                ('email', models.TextField(default=None)),
                ('password', models.TextField(default=None)),
            ],
        ),
    ]
